spring:
  application:
    name: school-bot
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    default-schema: school_db

telegram:
  bot:
    name: МАОУ СОШ №5 Расписание
    token: ${TELEGRAM_BOT_TOKEN}